// AUTO-GENERATED by /api/dev-assets — edit through the dropzone, not by hand.
import type { Slot, AssetManifest } from "@/components/assets/types";

export const slotIds = [
  "coverHero",
  "aiHighlightsCorpus",
  "aiHighlightsCorpus2",
  "iter1FilteredVideo",
  "iter1FilteredVideo2",
  "iter1FilteredVideo3",
  "iter2RadiologistOracle",
  "iter3Barista",
  "guardianHeldBack",
  "aiNativeRoundTrip",
  "agentSurface4up",
  "oracleQueryFlow",
  "baristaSuggestionCard",
] as const;

export type SixLabsAiSlotId = (typeof slotIds)[number];

export const sixLabsAiAssets: AssetManifest<SixLabsAiSlotId> = {
  coverHero: null,
  aiHighlightsCorpus: {"kind":"image","src":"/images/work/6labs-ai/aiHighlightsCorpus.jpg","alt":"aiHighlightsCorpus","width":2100,"height":900},
  aiHighlightsCorpus2: {"kind":"image","src":"/images/work/6labs-ai/aiHighlightsCorpus2.jpg","alt":"aiHighlightsCorpus2","width":1143,"height":1143},
  iter1FilteredVideo: {"kind":"image","src":"/images/work/6labs-ai/iter1FilteredVideo.jpg","alt":"iter1FilteredVideo","width":2001,"height":858},
  iter1FilteredVideo2: null,
  iter1FilteredVideo3: null,
  iter2RadiologistOracle: {"kind":"image","src":"/images/work/6labs-ai/iter2RadiologistOracle.jpg","alt":"iter2RadiologistOracle","width":2001,"height":858},
  iter3Barista: {"kind":"image","src":"/images/work/6labs-ai/iter3Barista.jpg","alt":"iter3Barista","width":2001,"height":858},
  guardianHeldBack: {"kind":"image","src":"/images/work/6labs-ai/guardianHeldBack.jpg","alt":"guardianHeldBack","width":2001,"height":858},
  aiNativeRoundTrip: {"kind":"image","src":"/images/work/6labs-ai/aiNativeRoundTrip.jpg","alt":"aiNativeRoundTrip","width":2667,"height":1143},
  agentSurface4up: {"kind":"image","src":"/images/work/6labs-ai/agentSurface4up.jpg","alt":"agentSurface4up","width":1920,"height":1080},
  oracleQueryFlow: {"kind":"image","src":"/images/work/6labs-ai/oracleQueryFlow.jpg","alt":"oracleQueryFlow","width":2738,"height":1540},
  baristaSuggestionCard: {"kind":"image","src":"/images/work/6labs-ai/baristaSuggestionCard.jpg","alt":"baristaSuggestionCard","width":1920,"height":1080},
};

export type { Slot };
