import { NextRequest } from "next/server";
import path from "node:path";
import { promises as fs } from "node:fs";
import { imageSize } from "image-size";

const PROJECTS = ["nowstudio", "float", "amway-india", "bluestacks", "6labs-ai", "ai-native-workflow", "gamification"] as const;
type ProjectId = (typeof PROJECTS)[number];

const SLOT_RE = /^[a-zA-Z][a-zA-Z0-9_-]{0,63}$/;
const ACCEPTED_EXT = new Set(["png", "jpg", "jpeg", "webp", "avif", "mp4", "webm"]);
const VIDEO_EXT = new Set(["mp4", "webm"]);
const MAX_FILE_BYTES = 20 * 1024 * 1024;

const ROOT = process.cwd();
const PUBLIC_WORK_DIR = path.resolve(ROOT, "public", "images", "work");
const APP_DIR = path.resolve(ROOT, "app");

function devOnly() {
  return process.env.NODE_ENV !== "development"
    ? new Response("Not found", { status: 404 })
    : null;
}

function getExt(name: string) {
  const ix = name.lastIndexOf(".");
  return ix === -1 ? "" : name.slice(ix + 1).toLowerCase();
}

function isProjectId(s: unknown): s is ProjectId {
  return typeof s === "string" && (PROJECTS as readonly string[]).includes(s);
}

async function deleteSlotFiles(project: ProjectId, slot: string) {
  const dir = path.join(PUBLIC_WORK_DIR, project);
  try {
    const entries = await fs.readdir(dir);
    await Promise.all(
      entries
        .filter((f) => f === slot || f.startsWith(`${slot}.`))
        .map((f) => fs.rm(path.join(dir, f), { force: true }))
    );
  } catch {
    // dir may not exist yet
  }
}

async function readManifest(project: ProjectId): Promise<Record<string, unknown>> {
  const file = path.join(APP_DIR, project, "assets.ts");
  const src = await fs.readFile(file, "utf8");
  // Naive but deterministic: extract { ... } after `${project}Assets:` prop or `<name>Assets =`
  const match = src.match(/Assets[^=]*=\s*({[\s\S]*?})\s*as\s*const|Assets[^=]*=\s*({[\s\S]*?});/);
  // Simpler: re-import via dynamic require by writing a small JSON shadow next to the manifest.
  // We'll instead parse by evaluating the right-hand side via a regex of the object literal.
  // But that's fragile. So we keep a sidecar JSON file as the actual store.
  void match;
  return {};
}

async function readShadow(project: ProjectId): Promise<Record<string, unknown>> {
  const file = path.join(APP_DIR, project, "assets.shadow.json");
  try {
    const txt = await fs.readFile(file, "utf8");
    return JSON.parse(txt);
  } catch {
    return {};
  }
}

async function writeShadow(project: ProjectId, data: Record<string, unknown>) {
  const file = path.join(APP_DIR, project, "assets.shadow.json");
  await fs.writeFile(file, JSON.stringify(data, null, 2) + "\n", "utf8");
}

async function readSlotIds(project: ProjectId): Promise<string[]> {
  const file = path.join(APP_DIR, project, "assets.ts");
  const src = await fs.readFile(file, "utf8");
  const match = src.match(/slotIds\s*=\s*\[([\s\S]*?)\]\s*as\s*const/);
  if (!match) return [];
  return Array.from(match[1].matchAll(/"([^"]+)"/g)).map((m) => m[1]);
}

function projectToCamel(project: string): string {
  // Convert hyphenated / numeric-prefixed project ids into valid JS identifiers.
  // Per-project overrides preserve legacy export names already imported elsewhere.
  const projectOverrides: Record<string, string> = {
    "amway-india": "amway", // legacy: pages import `amwayAssets`, not `amwayIndiaAssets`
    "6labs-ai": "sixLabsAi",
  };
  if (projectOverrides[project]) return projectOverrides[project];
  // Fallback: camelCase the parts.
  return project
    .split("-")
    .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");
}

function manifestSource(project: ProjectId, slotIds: string[], shadow: Record<string, unknown>) {
  const lines = slotIds.map((id) => {
    const entry = shadow[id];
    if (!entry) return `  ${id}: null,`;
    return `  ${id}: ${JSON.stringify(entry)},`;
  });
  const slotIdLines = slotIds.map((id) => `  "${id}",`).join("\n");
  const camelProject = projectToCamel(project);
  const exportName = `${camelProject}Assets`;
  const typeName = `${camelProject[0].toUpperCase()}${camelProject.slice(1)}SlotId`;
  return `// AUTO-GENERATED by /api/dev-assets — edit through the dropzone, not by hand.
import type { Slot, AssetManifest } from "@/components/assets/types";

export const slotIds = [
${slotIdLines}
] as const;

export type ${typeName} = (typeof slotIds)[number];

export const ${exportName}: AssetManifest<${typeName}> = {
${lines.join("\n")}
};

export type { Slot };
`;
}

async function rewriteManifest(project: ProjectId) {
  const ids = await readSlotIds(project);
  const shadow = await readShadow(project);
  const src = manifestSource(project, ids, shadow);
  await fs.writeFile(path.join(APP_DIR, project, "assets.ts"), src, "utf8");
}

function ensureSafePath(p: string) {
  const resolved = path.resolve(p);
  if (!resolved.startsWith(PUBLIC_WORK_DIR + path.sep) && resolved !== PUBLIC_WORK_DIR) {
    throw new Error("path-traversal");
  }
  return resolved;
}

export async function POST(req: NextRequest) {
  const blocked = devOnly();
  if (blocked) return blocked;

  const form = await req.formData();
  const project = form.get("project");
  const slot = form.get("slot");
  const files = form.getAll("files").filter((f): f is File => f instanceof File);

  if (!isProjectId(project)) return new Response("bad project", { status: 400 });
  if (typeof slot !== "string" || !SLOT_RE.test(slot)) return new Response("bad slot", { status: 400 });
  if (files.length !== 1) return new Response("expected exactly 1 file", { status: 400 });

  const file = files[0];
  if (file.size > MAX_FILE_BYTES) return new Response("file too large", { status: 413 });
  const ext = getExt(file.name);
  if (!ACCEPTED_EXT.has(ext)) return new Response(`unsupported extension: ${ext}`, { status: 400 });

  const slotIds = await readSlotIds(project);
  if (!slotIds.includes(slot)) return new Response(`unknown slot: ${slot}`, { status: 400 });

  const dir = path.join(PUBLIC_WORK_DIR, project);
  await fs.mkdir(dir, { recursive: true });
  await deleteSlotFiles(project, slot);

  const fileName = `${slot}.${ext}`;
  const filePath = ensureSafePath(path.join(dir, fileName));
  const buf = Buffer.from(await file.arrayBuffer());
  await fs.writeFile(filePath, buf);

  const publicSrc = `/images/work/${project}/${fileName}`;
  let dims: { width?: number; height?: number } = {};
  if (!VIDEO_EXT.has(ext)) {
    try {
      const out = imageSize(buf);
      if (out?.width && out?.height) dims = { width: out.width, height: out.height };
    } catch {
      // unreadable header — fall back to slot's declared aspect
    }
  }
  const entry =
    VIDEO_EXT.has(ext)
      ? { kind: "video" as const, src: publicSrc, alt: slot, ...dims }
      : { kind: "image" as const, src: publicSrc, alt: slot, ...dims };

  const shadow = await readShadow(project);
  shadow[slot] = entry;
  await writeShadow(project, shadow);
  await rewriteManifest(project);

  return Response.json({ ok: true, entry });
}

export async function DELETE(req: NextRequest) {
  const blocked = devOnly();
  if (blocked) return blocked;

  const url = new URL(req.url);
  const project = url.searchParams.get("project");
  const slot = url.searchParams.get("slot");

  if (!isProjectId(project)) return new Response("bad project", { status: 400 });
  if (!slot || !SLOT_RE.test(slot)) return new Response("bad slot", { status: 400 });

  const slotIds = await readSlotIds(project);
  if (!slotIds.includes(slot)) return new Response(`unknown slot: ${slot}`, { status: 400 });

  await deleteSlotFiles(project, slot);
  const shadow = await readShadow(project);
  delete shadow[slot];
  await writeShadow(project, shadow);
  await rewriteManifest(project);

  return Response.json({ ok: true });
}
