// AUTO-GENERATED by /api/dev-assets — edit through the dropzone, not by hand.
import type { Slot, AssetManifest } from "@/components/assets/types";

export const slotIds = [
  "dashboard",
  "flow01",
  "flow02",
  "flow03",
  "flow04",
  "flow05",
  "flow06",
  "pricingTable",
  "pricingTemplate",
  "rbac",
  "analytics",
  "discordBot",
  "testFlow",
  "iterV1",
  "iterV2",
  "iterV3",
  "decOnboardingKilled",
  "decOnboardingShipped",
  "decFlowKilled",
  "decFlowShipped",
  "v0Inherited",
  "v3Shipped",
] as const;

export type NowstudioSlotId = (typeof slotIds)[number];

export const nowstudioAssets: AssetManifest<NowstudioSlotId> = {
  dashboard: {"kind":"image","src":"/images/work/nowstudio/dashboard.jpg","alt":"dashboard","width":1920,"height":1080},
  flow01: {"kind":"image","src":"/images/work/nowstudio/flow01.png","alt":"flow01","width":2880,"height":1800},
  flow02: {"kind":"image","src":"/images/work/nowstudio/flow02.jpg","alt":"flow02","width":2880,"height":1800},
  flow03: {"kind":"image","src":"/images/work/nowstudio/flow03.png","alt":"flow03","width":2880,"height":1800},
  flow04: {"kind":"image","src":"/images/work/nowstudio/flow04.jpg","alt":"flow04","width":2880,"height":1800},
  flow05: {"kind":"image","src":"/images/work/nowstudio/flow05.jpg","alt":"flow05","width":2880,"height":1800},
  flow06: {"kind":"image","src":"/images/work/nowstudio/flow06.jpg","alt":"flow06","width":2880,"height":1800},
  pricingTable: {"kind":"image","src":"/images/work/nowstudio/pricingTable.jpg","alt":"pricingTable","width":2001,"height":858},
  pricingTemplate: {"kind":"image","src":"/images/work/nowstudio/pricingTemplate.jpg","alt":"pricingTemplate","width":2880,"height":1800},
  rbac: {"kind":"image","src":"/images/work/nowstudio/rbac.jpg","alt":"rbac","width":2001,"height":858},
  analytics: {"kind":"image","src":"/images/work/nowstudio/analytics.jpg","alt":"analytics","width":2001,"height":858},
  discordBot: {"kind":"image","src":"/images/work/nowstudio/discordBot.jpg","alt":"discordBot","width":2001,"height":858},
  testFlow: {"kind":"image","src":"/images/work/nowstudio/testFlow.jpg","alt":"testFlow","width":2001,"height":858},
  iterV1: {"kind":"image","src":"/images/work/nowstudio/iterV1.jpg","alt":"iterV1","width":2001,"height":858},
  iterV2: {"kind":"image","src":"/images/work/nowstudio/iterV2.jpg","alt":"iterV2","width":2001,"height":858},
  iterV3: {"kind":"image","src":"/images/work/nowstudio/iterV3.jpg","alt":"iterV3","width":2001,"height":858},
  decOnboardingKilled: {"kind":"image","src":"/images/work/nowstudio/decOnboardingKilled.jpg","alt":"decOnboardingKilled","width":2400,"height":1350},
  decOnboardingShipped: {"kind":"image","src":"/images/work/nowstudio/decOnboardingShipped.jpg","alt":"decOnboardingShipped","width":2400,"height":1350},
  decFlowKilled: {"kind":"image","src":"/images/work/nowstudio/decFlowKilled.jpg","alt":"decFlowKilled","width":2400,"height":1350},
  decFlowShipped: {"kind":"image","src":"/images/work/nowstudio/decFlowShipped.jpg","alt":"decFlowShipped","width":2400,"height":1350},
  v0Inherited: {"kind":"image","src":"/images/work/nowstudio/v0Inherited.jpg","alt":"v0Inherited","width":1920,"height":1080},
  v3Shipped: {"kind":"image","src":"/images/work/nowstudio/v3Shipped.jpg","alt":"v3Shipped","width":1920,"height":1080},
};

export type { Slot };
