// AUTO-GENERATED by /api/dev-assets — edit through the dropzone, not by hand.
import type { Slot, AssetManifest } from "@/components/assets/types";

export const slotIds = [
  "coverHero",
  "systemOverview",
  "forgeScreenshot",
  "landScreenshot",
  "tetherScreenshot",
  "parityScreenshot",
  "glyphScreenshot",
  "sweepScreenshot",
  "tokenBinderScreenshot",
  "workshopArtifact",
  "baristaFigmaToCode",
  "baristaCodeToFrontend",
] as const;

export type AiNativeWorkflowSlotId = (typeof slotIds)[number];

export const aiNativeWorkflowAssets: AssetManifest<AiNativeWorkflowSlotId> = {
  coverHero: null,
  systemOverview: null,
  forgeScreenshot: {"kind":"image","src":"/images/work/ai-native-workflow/forgeScreenshot.jpg","alt":"forgeScreenshot","width":1800,"height":1800},
  landScreenshot: {"kind":"image","src":"/images/work/ai-native-workflow/landScreenshot.jpg","alt":"landScreenshot","width":1800,"height":1800},
  tetherScreenshot: {"kind":"image","src":"/images/work/ai-native-workflow/tetherScreenshot.jpg","alt":"tetherScreenshot","width":1800,"height":1800},
  parityScreenshot: {"kind":"image","src":"/images/work/ai-native-workflow/parityScreenshot.jpg","alt":"parityScreenshot","width":1800,"height":1800},
  glyphScreenshot: {"kind":"image","src":"/images/work/ai-native-workflow/glyphScreenshot.jpg","alt":"glyphScreenshot","width":1800,"height":1800},
  sweepScreenshot: {"kind":"image","src":"/images/work/ai-native-workflow/sweepScreenshot.jpg","alt":"sweepScreenshot","width":1800,"height":1800},
  tokenBinderScreenshot: {"kind":"image","src":"/images/work/ai-native-workflow/tokenBinderScreenshot.jpg","alt":"tokenBinderScreenshot","width":1800,"height":1800},
  workshopArtifact: {"kind":"image","src":"/images/work/ai-native-workflow/workshopArtifact.jpg","alt":"workshopArtifact","width":2667,"height":1143},
  baristaFigmaToCode: {"kind":"image","src":"/images/work/ai-native-workflow/baristaFigmaToCode.jpg","alt":"baristaFigmaToCode","width":2001,"height":858},
  baristaCodeToFrontend: {"kind":"image","src":"/images/work/ai-native-workflow/baristaCodeToFrontend.jpg","alt":"baristaCodeToFrontend","width":2001,"height":858},
};

export type { Slot };
