// AUTO-GENERATED by /api/dev-assets — edit through the dropzone, not by hand.
import type { Slot, AssetManifest } from "@/components/assets/types";

export const slotIds = [
  "coverHero",
  "systemMap",
  "bsxQuests",
  "paymentsCashback",
  "paymentsMiniGames",
  "nowcafeBots",
  "nowggProfile",
  "playpalMobile",
  "gameRoom",
  "snakePlanet",
  "heldBack",
  "loopDiagram",
  "currencyLayer",
] as const;

export type GamificationSlotId = (typeof slotIds)[number];

export const gamificationAssets: AssetManifest<GamificationSlotId> = {
  coverHero: null,
  systemMap: null,
  bsxQuests: {"kind":"image","src":"/images/work/gamification/bsxQuests.jpg","alt":"bsxQuests","width":2001,"height":858},
  paymentsCashback: {"kind":"image","src":"/images/work/gamification/paymentsCashback.jpg","alt":"paymentsCashback","width":2001,"height":858},
  paymentsMiniGames: {"kind":"image","src":"/images/work/gamification/paymentsMiniGames.jpg","alt":"paymentsMiniGames","width":2001,"height":858},
  nowcafeBots: {"kind":"image","src":"/images/work/gamification/nowcafeBots.jpg","alt":"nowcafeBots","width":2001,"height":858},
  nowggProfile: {"kind":"image","src":"/images/work/gamification/nowggProfile.jpg","alt":"nowggProfile","width":2001,"height":858},
  playpalMobile: {"kind":"image","src":"/images/work/gamification/playpalMobile.jpg","alt":"playpalMobile","width":2001,"height":858},
  gameRoom: {"kind":"image","src":"/images/work/gamification/gameRoom.jpg","alt":"gameRoom","width":2001,"height":858},
  snakePlanet: {"kind":"image","src":"/images/work/gamification/snakePlanet.jpg","alt":"snakePlanet","width":2001,"height":858},
  heldBack: null,
  loopDiagram: null,
  currencyLayer: {"kind":"image","src":"/images/work/gamification/currencyLayer.jpg","alt":"currencyLayer","width":2001,"height":858},
};

export type { Slot };
